module power{
	interface PowerPSActuator : framework::GenericActuator{
                void setOutput(in simulation::power::PowerPS source);
		simulation::power::PowerPS getOutput();
        };
	interface PowerStoreActuator : framework::GenericActuator{
                void setOutput(in simulation::power::PowerStore source);
		simulation::power::PowerStore getOutput();
        };
	interface PowerStoreLevelActuator : PowerStoreActuator{};
	
	interface PowerInFlowRateActuator : framework::GenericActuator{
		void setOutput(in framework::PowerConsumer pConsumer, in long pIndex);
		framework::PowerConsumer getOutput();
		long getIndex();
	};
	interface PowerOutFlowRateActuator : framework::GenericActuator{
		void setOutput(in framework::PowerProducer pProducer, in long pIndex);
		framework::PowerProducer getOutput();
		long getIndex();
	};
};
