module biosim{

        module idl{
		
		module framework{
			interface BioModule{
				void tick();
				string getModuleName();
			};
		};
		
		module util{
			interface BioSimUtils{
			};
		};

                module crew{
                        interface Activity{
                                string getName();
                                long getTimeLength();
                        };
                        interface CrewPerson{
                                Object getCurrentActivity();
                                void setCurrentActivity(in Object newActivity);
                                string getName();
                        };
                        interface CrewGroup : framework::BioModule{
                                Object getScheduledActivityByName(in string name);
                                Object getScheduledActivityByOrder(in long order);
                                Object getCrewPerson(in string name);
                                Object createCrewPerson(in string name);
                        };
                };

                module power{
                        interface PowerPS : framework::BioModule{
                                float getPowerProduced();
                        };
                        interface PowerStore : framework::BioModule{
                                void setPowerCapacity(in float watts);
                                void setPowerLevel(in float watts);
                                float addPower(in float watts);
                                float takePower(in float watts);
                                float getPowerLevel();
                        };
                };

                module air{
                        interface AirRS : framework::BioModule{
                                float getPowerConsumed();
                                float getCO2Consumed();
                                float getO2Produced();
                        };
                        interface O2Store : framework::BioModule{
                                void setO2Capacity(in float liters);
                                void setO2Level(in float liters);
                                float addO2(in float liters);
                                float takeO2(in float liters);
                                float getO2Level();
                        };
                        interface CO2Store : framework::BioModule{
                                void setCO2Capacity(in float liters);
                                void setCO2Level(in float liters);
                                float addCO2(in float liters);
                                float takeCO2(in float liters);
                                float getCO2Level();
                        };
                };

                module food{
                        interface BiomassRS : framework::BioModule{
                                float getPowerConsumed();
                                float getGreyWaterConsumed();
                                float getBiomassProduced();
                        };
                        interface BiomassStore : framework::BioModule{
                                void setBiomassCapacity(in float kilograms);
                                void setBiomassLevel(in float kilograms);
                                float addBiomass(in float kilograms);
                                float takeBiomass(in float kilograms);
                                float getBiomassLevel();
                        };
                        interface FoodProcessor : framework::BioModule{
                                float getBiomassConsumed();
                                float getPowerConsumed();
                                float getFoodProduced();
                        };
                        interface FoodStore : framework::BioModule{
                                void setFoodCapacity(in float kilograms);
                                void setFoodLevel(in float kilograms);
                                float addFood(in float kilograms);
                                float takeFood(in float kilograms);
                                float getFoodLevel();
                        };
                };

                module environment{
                        interface SimEnvironment : framework::BioModule{
                                void setCO2Capacity(in float liters);
                                void setCO2Level(in float liters);
                                void setO2Capacity(in float liters);
                                void setO2Level(in float liters);
                                float getO2Level();
                                float getCO2Level();
                                float addCO2(in float liters);
                                float addO2(in float liters);
                                float takeO2(in float liters);
                                float takeCO2(in float liters);
				long getTicks();
                        };
                };

                module water{
                        interface WaterRS : framework::BioModule{
                                float getPotableWaterProduced();
                                float getGreyWaterProduced();
                                float getPowerConsumed();
                                float getDirtyWaterConsumed();
                        };
                        interface PotableWaterStore : framework::BioModule{
                                void setWaterCapacity(in float liters);
                                void setWaterLevel(in float liters);
                                float takeWater(in float liters);
                                float addWater(in float liters);
                                float getWaterLevel();
                        };
                        interface GreyWaterStore : framework::BioModule{
                                void setWaterCapacity(in float liters);
                                void setWaterLevel(in float liters);
                                float takeWater(in float liters);
                                float addWater(in float liters);
                                float getWaterLevel();
                        };
                        interface DirtyWaterStore : framework::BioModule{
                                void setWaterCapacity(in float liters);
                                void setWaterLevel(in float liters);
                                float takeWater(in float liters);
                                float addWater(in float liters);
                                float getWaterLevel();
                        };
                };
        };
};
















