module framework{
        interface Malfunction{
                MalfunctionIntensity getIntensity();
                long long getID();
                string getName();
                boolean hasPerformed();
                void setPerformed(in boolean pPerformed);
                MalfunctionLength getLength();
                void repair();
                boolean isRepaired();
        };
        interface BioModule{
                void tick();
                string getModuleName();
                void reset();
                void setLogging(in boolean pLogging);
                boolean isLogging();
                void setStochasticIntensity(in StochasticIntensity pIntensity);
                StochasticIntensity getStochasticIntensity();
                Malfunction startMalfunction(in MalfunctionIntensity pIntensity, in MalfunctionLength pLength);
                void fixMalfunction(in long long id);
                void fixAllMalfunctions();
                boolean isMalfunctioning();
                StringList getMalfunctionNames();
                MalfunctionList getMalfunctions();
                void maitenance();
                void repair(in long long id);
        };
        interface Store : BioModule{
                void setCapacity(in float metricAmount);
                void setLevel(in float metricAmount);
                float add(in float metricAmount);
                float take(in float metricAmount);
                float getLevel();
                float getCapacity();
        };
        interface BioDriver{
                boolean isPaused();
                boolean isStarted();
                void spawnSimulation();
                void spawnSimulationTillDead();
                void spawnSimulationTillN(in long nTicks);
                void pauseSimulation();
                void endSimulation();
                boolean simulationHasStarted();
                void advanceOneTick();
                void resumeSimulation();
                void setLogging(in boolean pLogSim);
                boolean isLogging();
                void setDriverPauseLength(in long pDriverPauseLength);
                long getDriverPauseLength();
                string getName();
                boolean isDone();
                long getTicks();
                void reset();
                boolean isLooping();
                void setLooping(in boolean pLoop);
                void setInitialization(in BioDriverInit myInit);
                void setStochasticIntensity(in StochasticIntensity pIntensity);
                void startMalfunction(in MalfunctionIntensity pIntensity, in MalfunctionLength pLength);
        };
	interface Injector : BioModule, PowerConsumer, PotableWaterConsumer, GreyWaterConsumer, DirtyWaterConsumer, O2Consumer, CO2Consumer, AirConsumer, BiomassConsumer, FoodConsumer, O2AirConsumer, CO2AirConsumer, OtherAirConsumer, PowerProducer, PotableWaterProducer, GreyWaterProducer, DirtyWaterProducer, O2Producer, CO2Producer, AirProducer, BiomassProducer, FoodProducer, O2AirProducer, CO2AirProducer, OtherAirProducer{
	};
	interface Accumulator : BioModule, PowerConsumer, PotableWaterConsumer, GreyWaterConsumer, DirtyWaterConsumer, O2Consumer, CO2Consumer, AirConsumer, BiomassConsumer, FoodConsumer, O2AirConsumer, CO2AirConsumer, OtherAirConsumer, PowerProducer, PotableWaterProducer, GreyWaterProducer, DirtyWaterProducer, O2Producer, CO2Producer, AirProducer, BiomassProducer, FoodProducer, O2AirProducer, CO2AirProducer, OtherAirProducer{
	};
        interface PowerConsumer{
                void setPowerInputFlowrate(in float watts, in long index);
                float getPowerInputFlowrate(in long index);
                void setPowerInputs(in ::power::PowerStoreList sources, in FloatList flowRates);
		power::PowerStoreList getPowerInputs();
        };
        interface PotableWaterConsumer{
                void setPotableWaterInputFlowrate(in float liters, in long index);
                float getPotableWaterInputFlowrate(in long index);
                void setPotableWaterInputs(in water::PotableWaterStoreList sources, in FloatList flowRates);
		water::PotableWaterStoreList getPotableWaterInputs();
        };
        interface GreyWaterConsumer{
                void setGreyWaterInputFlowrate(in float liters, in long index);
                float getGreyWaterInputFlowrate(in long index);
                void setGreyWaterInputs(in water::GreyWaterStoreList sources, in FloatList flowRates);
		water::GreyWaterStoreList getGreyWaterInputs();
        };
        interface DirtyWaterConsumer{
                void setDirtyWaterInputFlowrate(in float liters, in long index);
                float getDirtyWaterInputFlowrate(in long index);
                void setDirtyWaterInputs(in water::DirtyWaterStoreList sources, in FloatList flowRates);
		water::DirtyWaterStoreList getDirtyWaterInputs();
        };
        interface O2Consumer{
                void setO2InputFlowrate(in float liters, in long index);
                float getO2InputFlowrate(in long index);
                void setO2Inputs(in air::O2StoreList sources, in FloatList flowRates);
		air::O2StoreList getO2Inputs();
        };
        interface CO2Consumer{
                void setCO2InputFlowrate(in float liters, in long index);
                float getCO2InputFlowrate(in long index);
                void setCO2Inputs(in air::CO2StoreList sources, in FloatList flowRates);
		air::CO2StoreList getCO2Inputs();
        };
        interface AirConsumer{
                void setAirInputFlowrate(in float liters, in long index);
                float getAirInputFlowrate(in long index);
                void setAirInputs(in environment::SimEnvironmentList sources, in FloatList flowRates);
		environment::SimEnvironmentList getAirInputs();
        };
        interface BiomassConsumer{
                void setBiomassInputFlowrate(in float kilograms, in long index);
                float getBiomassInputFlowrate(in long index);
                void setBiomassInputs(in food::BiomassStoreList sources, in FloatList flowRates);
		food::BiomassStoreList getBiomassInputs();
        };
        interface FoodConsumer{
                void setFoodInputFlowrate(in float kilograms, in long index);
                float getFoodInputFlowrate(in long index);
                void setFoodInputs(in food::FoodStoreList sources, in FloatList flowRates);
		food::FoodStoreList getFoodInputs();
        };
	interface PowerProducer{
                void setPowerOutputFlowrate(in float watts, in long index);
                float getPowerOutputFlowrate(in long index);
                void setPowerOutputs(in ::power::PowerStoreList destinations, in FloatList flowRates);
		power::PowerStoreList getPowerOutputs();
        };
        interface PotableWaterProducer{
                void setPotableWaterOutputFlowrate(in float liters, in long index);
                float getPotableWaterOutputFlowrate(in long index);
                void setPotableWaterOutputs(in water::PotableWaterStoreList destinations, in FloatList flowRates);
		water::PotableWaterStoreList getPotableWaterOutputs();
        };
        interface GreyWaterProducer{
                void setGreyWaterOutputFlowrate(in float liters, in long index);
                float getGreyWaterOutputFlowrate(in long index);
                void setGreyWaterOutputs(in water::GreyWaterStoreList destinations, in FloatList flowRates);
		water::GreyWaterStoreList getGreyWaterOutputs();
        };
        interface DirtyWaterProducer{
                void setDirtyWaterOutputFlowrate(in float liters, in long index);
                float getDirtyWaterOutputFlowrate(in long index);
                void setDirtyWaterOutputs(in water::DirtyWaterStoreList destinations, in FloatList flowRates);
		water::DirtyWaterStoreList getDirtyWaterOutputs();
        };
        interface O2Producer{
                void setO2OutputFlowrate(in float liters, in long index);
                float getO2OutputFlowrate(in long index);
                void setO2Outputs(in air::O2StoreList destinations, in FloatList flowRates);
		air::O2StoreList getO2Outputs();
        };
        interface CO2Producer{
                void setCO2OutputFlowrate(in float liters, in long index);
                float getCO2OutputFlowrate(in long index);
                void setCO2Outputs(in air::CO2StoreList destinations, in FloatList flowRates);
		air::CO2StoreList getCO2Outputs();
        };
        interface AirProducer{
                void setAirOutputFlowrate(in float liters, in long index);
                float getAirOutputFlowrate(in long index);
                void setAirOutputs(in environment::SimEnvironmentList destinations, in FloatList flowRates);
		environment::SimEnvironmentList getAirOutputs();
        };
        interface BiomassProducer{
                void setBiomassOutputFlowrate(in float kilograms, in long index);
                float getBiomassOutputFlowrate(in long index);
                void setBiomassOutputs(in food::BiomassStoreList destinations, in FloatList flowRates);
		food::BiomassStoreList getBiomassOutputs();
        };
        interface FoodProducer{
                void setFoodOutputFlowrate(in float kilograms, in long index);
                float getFoodOutputFlowrate(in long index);
                void setFoodOutputs(in food::FoodStoreList destinations, in FloatList flowRates);
		food::FoodStoreList getFoodOutputs();
        };
	interface LightConsumer{
                void setLightInput(in environment::SimEnvironment source);
		environment::SimEnvironment getLightInput();
        };
	interface O2AirConsumer{
                void setO2AirInputFlowrate(in float liters, in long index);
                float getO2AirInputFlowrate(in long index);
                void setO2AirInput(in environment::SimEnvironmentList source, in FloatList flowRates);
		environment::SimEnvironmentList getO2AirInputs();
        };
	interface CO2AirConsumer{
                void setCO2AirInputFlowrate(in float liters, in long index);
                float getCO2AirInputFlowrate(in long index);
                void setCO2AirInput(in environment::SimEnvironmentList source, in FloatList flowRates);
		environment::SimEnvironmentList getCO2AirInputs();
        };
	interface OtherAirConsumer{
                void setOtherAirInputFlowrate(in float liters, in long index);
                float getOtherAirInputFlowrate(in long index);
                void setOtherAirInput(in environment::SimEnvironmentList source, in FloatList flowRates);
		environment::SimEnvironmentList getOtherAirInputs();
        };
	interface O2AirProducer{
                void setO2AirOutputFlowrate(in float liters, in long index);
                float getO2AirOutputFlowrate(in long index);
                void setO2AirOutput(in environment::SimEnvironmentList destination, in FloatList flowRates);
		environment::SimEnvironmentList getO2AirOutputs();
        };
	interface CO2AirProducer{
                void setCO2AirOutputFlowrate(in float liters, in long index);
                float getCO2AirOutputFlowrate(in long index);
                void setCO2AirOutput(in environment::SimEnvironmentList destination, in FloatList flowRates);
		environment::SimEnvironmentList getCO2AirOutputs();
        };
	interface OtherAirProducer{
                void setOtherAirOutputFlowrate(in float liters, in long index);
                float getOtherAirOutputFlowrate(in long index);
                void setOtherAirOutput(in environment::SimEnvironmentList destination, in FloatList flowRates);
		environment::SimEnvironmentList getOtherAirOutputs();
        };
};
