module environment{
	interface EnvironmentSensor{
		void setInput(in simulation::environment::SimEnvironment source);
		simulation::environment::SimEnvironment getInput();
	};
        interface AirLevelSensor : EnvironmentSensor{};
	interface LightLevelSensor : EnvironmentSensor{};
	interface O2AirLevelSensor : EnvironmentSensor{};
	interface CO2AirLevelSensor : EnvironmentSensor{};
	interface otherAirLevelSensor : EnvironmentSensor{};
};
