module environment{
	interface EnvironmentSensor : framework::GenericSensor{
		void setInput(in simulation::environment::SimEnvironment source);
		simulation::environment::SimEnvironment getInput();
	};
        interface AirLevelSensor : EnvironmentSensor{};
	interface LightLevelSensor : EnvironmentSensor{};
	interface O2AirLevelSensor : EnvironmentSensor{};
	interface CO2AirLevelSensor : EnvironmentSensor{};
	interface otherAirLevelSensor : EnvironmentSensor{};
	interface AirFlowRateSensor : framework::GenericSensor{
		void setInput(in simulation::environment::AirProducer source, in long indexSource, in simulation::environment::AirConsumer destination, in long indexDestination);
		simulation::environment::AirProducer getProducer();
		simulation::environment::AirConsumer getConsumer();
	};
	interface O2AirFlowRateSensor : framework::GenericSensor{
		void setInput(in simulation::environment::O2AirProducer source, in long indexSource, in simulation::environment::O2AirConsumer destination, in long indexDestination);
		simulation::environment::O2AirProducer getProducer();
		simulation::environment::O2AirConsumer getConsumer();
	};
	interface CO2AirFlowRateSensor : framework::GenericSensor{
		void setInput(in simulation::environment::CO2AirProducer source, in long indexSource, in simulation::environment::CO2AirConsumer destination, in long indexDestination);
		simulation::environment::CO2AirProducer getProducer();
		simulation::environment::CO2AirConsumer getConsumer();
	};
};
