module food{
	interface BiomassStoreSensor : framework::GenericSensor{
                void setInput(in simulation::food::BiomassStore source);
		simulation::food::BiomassStore getInput();
	};
        interface BiomassStoreLevelSensor : BiomassStoreSensor{};
	interface FoodStoreSensor : framework::GenericSensor{
                void setInput(in simulation::food::FoodStore source);
		simulation::food::FoodStore getInput();
	};
        interface FoodStoreLevelSensor : FoodStoreSensor{};
	
	interface BiomassRSSensor : framework::GenericSensor{
                void setInput(in simulation::food::BiomassRS source);
		simulation::food::BiomassRS getInput();
        };
	
	interface FoodProcessorSensor : framework::GenericSensor{
                void setInput(in simulation::food::FoodProcessor source);
		simulation::food::FoodProcessor getInput();
        };
	
	interface BiomassInFlowRateSensor : framework::GenericSensor{
		void setInput(in framework::BiomassConsumer pConsumer, in long pIndex);
		framework::BiomassConsumer getInput();
		long getIndex();
	};
	interface BiomassOutFlowRateSensor : framework::GenericSensor{
		void setInput(in framework::BiomassProducer pProducer, in long pIndex);
		framework::BiomassProducer getInput();
		long getIndex();
	};
	
	interface FoodInFlowRateSensor : framework::GenericSensor{
		void setInput(in framework::FoodConsumer pConsumer, in long pIndex);
		framework::FoodConsumer getInput();
		long getIndex();
	};
	interface FoodOutFlowRateSensor : framework::GenericSensor{
		void setInput(in framework::FoodProducer pProducer, in long pIndex);
		framework::FoodProducer getInput();
		long getIndex();
	};
};
