module power{
	interface PowerPSSensor : framework::GenericSensor{
                void setInput(in simulation::power::PowerPS source);
		simulation::power::PowerPS getInput();
        };
	interface PowerStoreSensor : framework::GenericSensor{
                void setInput(in simulation::power::PowerStore source);
		simulation::power::PowerStore getInput();
        };
	interface PowerStoreLevelSensor : PowerStoreSensor{};
	
	interface PowerInFlowRateSensor : framework::GenericSensor{
		void setInput(in simulation::power::PowerConsumer pConsumer, in long pIndex);
		simulation::power::PowerConsumer getInput();
		long getIndex();
	};
	interface PowerOutFlowRateSensor : framework::GenericSensor{
		void setInput(in simulation::power::PowerProducer pProducer, in long pIndex);
		simulation::power::PowerProducer getInput();
		long getIndex();
	};
};
