module water{
	interface PotableWaterStoreSensor : framework::GenericSensor{
		void setInput(in simulation::water::PotableWaterStore source);
		simulation::water::PotableWaterStore getInput();
	};
	interface GreyWaterStoreSensor : framework::GenericSensor{
		void setInput(in simulation::water::GreyWaterStore source);
		simulation::water::GreyWaterStore getInput();
	};
	interface DirtyWaterStoreSensor : framework::GenericSensor{
		void setInput(in simulation::water::DirtyWaterStore source);
		simulation::water::DirtyWaterStore getInput();
	};
        interface PotableWaterLevelSensor : PotableWaterStoreSensor{};
        interface GreyWaterLevelSensor : GreyWaterStoreSensor{};
        interface DirtyWaterLevelSensor : DirtyWaterStoreSensor{};
	interface PotableWaterFlowRateSensor : framework::GenericSensor{
		void setInput(in simulation::water::PotableWaterProducer source, in long indexSource, in simulation::water::PotableWaterConsumer destination, in long indexDestination);
		simulation::water::PotableWaterProducer getProducer();
		simulation::water::PotableWaterConsumer getConsumer();
	};
	interface GreyWaterFlowRateSensor : framework::GenericSensor{
		void setInput(in simulation::water::GreyWaterProducer source, in long indexSource, in simulation::water::GreyWaterConsumer destination, in long indexDestination);
		simulation::water::GreyWaterProducer getProducer();
		simulation::water::GreyWaterConsumer getConsumer();
	};
	interface DirtyWaterFlowRateSensor : framework::GenericSensor{
		void setInput(in simulation::water::DirtyWaterProducer source, in long indexSource, in simulation::water::DirtyWaterConsumer destination, in long indexDestination);
		simulation::water::DirtyWaterProducer getProducer();
		simulation::water::DirtyWaterConsumer getConsumer();
	};
};
