module water{
	interface PotableWaterStoreSensor{
		void setInput(in simulation::water::PotableWaterStore source);
		simulation::water::PotableWaterStore getInput();
	};
	interface GreyWaterStoreSensor{
		void setInput(in simulation::water::GreyWaterStore source);
		simulation::water::GreyWaterStore getInput();
	};
	interface DirtyWaterStoreSensor{
		void setInput(in simulation::water::DirtyWaterStore source);
		simulation::water::DirtyWaterStore getInput();
	};
        interface PotableWaterLevelSensor : PotableWaterStoreSensor{};
        interface GreyWaterLevelSensor : GreyWaterStoreSensor{};
        interface DirtyWaterLevelSensor : DirtyWaterStoreSensor{};
};
