// -*- C++ -*-
//
// $Id$

// ****  Code generated by the The ACE ORB (TAO) IDL Compiler ****
// TAO and the TAO IDL Compiler have been developed by:
//       Center for Distributed Object Computing
//       Washington University
//       St. Louis, MO
//       USA
//       http://www.cs.wustl.edu/~schmidt/doc-center.html
// and
//       Distributed Object Computing Laboratory
//       University of California at Irvine
//       Irvine, CA
//       USA
//       http://doc.ece.uci.edu/
//
// Information about TAO is available at:
//     http://www.cs.wustl.edu/~schmidt/TAO.html

#ifndef _TAO_IDL_BIOSIMS_T_H_
#define _TAO_IDL_BIOSIMS_T_H_

#if defined(_MSC_VER)
#if (_MSC_VER >= 1200)
#pragma warning(push)
#endif /* _MSC_VER >= 1200 */
#pragma warning(disable:4250)
#endif /* _MSC_VER */

#if defined (ACE_HAS_USING_KEYWORD)
TAO_NAMESPACE  POA_biosim
{
  TAO_NAMESPACE  idl
  {
    TAO_NAMESPACE  framework
    {
      // TIE class: Refer to CORBA v2.2, Section 20.34.4
      template <class T>
      class  BioDriver_tie : public BioDriver
      {
      public:
        BioDriver_tie (T &t);
        // the T& ctor
        BioDriver_tie (T &t, PortableServer::POA_ptr poa);
        // ctor taking a POA
        BioDriver_tie (T *tp, CORBA::Boolean release=1);
        // ctor taking pointer and an ownership flag
        BioDriver_tie (T *tp, PortableServer::POA_ptr poa, CORBA::Boolean release=1);
        // ctor with T*, ownership flag and a POA
        ~BioDriver_tie (void);
        // dtor
        
        // TIE specific functions
        T *_tied_object (void);
        // return the underlying object
        void _tied_object (T &obj);
        // set the underlying object
        void _tied_object (T *obj, CORBA::Boolean release=1);
        // set the underlying object and the ownership flag
        CORBA::Boolean _is_owner (void);
        // do we own it
        void _is_owner (CORBA::Boolean b);
        // set the ownership
        
        // overridden ServantBase operations
        PortableServer::POA_ptr _default_POA (
            CORBA::Environment &ACE_TRY_ENV = 
              TAO_default_environment ()
          );
        CORBA::Boolean isPaused (
            
          )
          ACE_THROW_SPEC ((
            CORBA::SystemException
          ));
        
                CORBA::Boolean isStarted (
            
          )
          ACE_THROW_SPEC ((
            CORBA::SystemException
          ));
        
                void spawnSimulation (
            
          )
          ACE_THROW_SPEC ((
            CORBA::SystemException
          ));
        
                void spawnSimulationTillDead (
            
          )
          ACE_THROW_SPEC ((
            CORBA::SystemException
          ));
        
                void spawnSimulationTillN (
            CORBA::Long nTicks
          )
          ACE_THROW_SPEC ((
            CORBA::SystemException
          ));
        
                void pauseSimulation (
            
          )
          ACE_THROW_SPEC ((
            CORBA::SystemException
          ));
        
                void endSimulation (
            
          )
          ACE_THROW_SPEC ((
            CORBA::SystemException
          ));
        
                CORBA::Boolean simulationHasStarted (
            
          )
          ACE_THROW_SPEC ((
            CORBA::SystemException
          ));
        
                void advanceOneTick (
            
          )
          ACE_THROW_SPEC ((
            CORBA::SystemException
          ));
        
                void resumeSimulation (
            
          )
          ACE_THROW_SPEC ((
            CORBA::SystemException
          ));
        
                void setLogging (
            CORBA::Boolean pLogSim
          )
          ACE_THROW_SPEC ((
            CORBA::SystemException
          ));
        
                CORBA::Boolean isLogging (
            
          )
          ACE_THROW_SPEC ((
            CORBA::SystemException
          ));
        
                void setDriverPauseLength (
            CORBA::Long pDriverPauseLength
          )
          ACE_THROW_SPEC ((
            CORBA::SystemException
          ));
        
                CORBA::Long getDriverPauseLength (
            
          )
          ACE_THROW_SPEC ((
            CORBA::SystemException
          ));
        
              private:
        T *ptr_;
        PortableServer::POA_var poa_;
        CORBA::Boolean rel_;
        
        // copy and assignment are not allowed
        BioDriver_tie (const BioDriver_tie &);
        void operator= (const BioDriver_tie &);
      };

    }
    TAO_NAMESPACE_CLOSE // module biosim::idl::framework
  }
  TAO_NAMESPACE_CLOSE // module biosim::idl
}
TAO_NAMESPACE_CLOSE // module biosim
#endif /* ACE_HAS_USING_KEYWORD */

#if defined (__ACE_INLINE__)
#include "biosimS_T.i"
#endif /* defined INLINE */


#if defined (ACE_TEMPLATES_REQUIRE_SOURCE)
#include "biosimS_T.cpp"
#endif /* defined REQUIRED SOURCE */


#if defined (ACE_TEMPLATES_REQUIRE_PRAGMA)
#pragma implementation ("biosimS_T.cpp")
#endif /* defined REQUIRED PRAGMA */

#if defined(_MSC_VER) && (_MSC_VER >= 1200)
#pragma warning(pop)
#endif /* _MSC_VER */

#endif /* ifndef */
