module crew{
        interface Activity{
                string getName();
                long getTimeLength();
                long getActivityIntensity();
        };
        interface RepairActivity : Activity{
                string getModuleNameToRepair();
                long long getMalfunctionIDToRepair();
        };
        interface MaitenanceActivity : Activity{
                string getModuleToMaitenance();
        };
        interface CrewPerson{
                Activity getCurrentActivity();
                void setCurrentActivity(in Activity newActivity);
                long getOrderOfScheduledActivity(in string name);
                void insertActivityInSchedule(in Activity newActivity, in long order);
                void insertActivityInScheduleNow(in Activity newActivity);
                void sicken();
                string getName();
                float getAge();
                float getWeight();
                long getTimeActivityPerformed();
                Sex getSex();
                boolean isStarving();
                boolean isPoisoned();
                boolean isThirsty();
                boolean isSuffocating();
                boolean isDead();
                float getGreyWaterProduced();
                float getDirtyWaterProduced();
                float getPotableWaterConsumed();
                float getFoodConsumed();
                float getCO2Produced();
                float getO2Consumed();
                Activity getActivityByName(in string name);
                Activity getScheduledActivityByOrder(in long order);
        };
	// framework::AirConsumer, framework::PotableWaterConsumer, framework::FoodConsumer, framework::AirProducer, framework::GreyWaterProducer, framework::DirtyWaterProducer
        interface CrewGroup : framework::BioModule{
                CrewPerson getCrewPerson(in string name);
                CrewPerson createCrewPerson(in string name, in float age, in float weight, in Sex pSex);
                CrewPersonList getCrewPeople();
                void scheduleRepair(in string moduleName, in long long malfunctionID, in long timeLength);
                long getCrewSize();
                float getGreyWaterProduced();
                float getDirtyWaterProduced();
                float getPotableWaterConsumed();
                float getFoodConsumed();
                float getCO2Produced();
                float getO2Consumed();
                boolean isDead();
        };
};

