module food{
        interface BiomassRS : framework::BioModule, framework::PowerConsumer, framework::PotableWaterConsumer, framework::GreyWaterConsumer, framework::BiomassProducer{
                ShelfList getShelves();
                float getTotalPotableWaterConsumed();
                float getTotalGreyWaterConsumed();
                float getTotalPowerConsumed();
                float getTotalPlantArea();
                float getTotalBiomassProduced();
                StringList getPlantTypes();
                float getTotalO2Produced();
                float getTotalCO2Consumed();
        };
	
        interface BiomassStore : framework::Store{};
	
        interface FoodProcessor : framework::BioModule, framework::PowerConsumer, framework::BiomassConsumer, framework::FoodProducer{
                float getBiomassConsumed();
                float getPowerConsumed();
                float getFoodProduced();
                boolean hasPower();
                boolean hasBiomass();
        };
	
        interface FoodStore : framework::Store{};
	
        interface Shelf{
                float getArea();
                float getPowerConsumed();
                float getGreyWaterConsumed();
                float getPotableWaterConsumed();
                float getO2Produced();
                float getCO2Consumed();
                float getBiomassProduced();
                boolean hasWater();
                boolean hasLight();
                boolean isDead();
                boolean hasCO2();
        };
};
