module crew{
        interface CrewSensor : framework::GenericSensor{
                void setInput(in simulation::crew::CrewGroup source);
		simulation::crew::CrewGroup getInput();
	};
	interface CrewActivitySensor : CrewSensor{};
};
