module environment{
	interface EnvironmentSensor : framework::GenericSensor{
		void setInput(in simulation::environment::SimEnvironment source);
		simulation::environment::SimEnvironment getInput();
	};
        interface AirLevelSensor : EnvironmentSensor{};
	interface LightLevelSensor : EnvironmentSensor{};
	interface O2AirLevelSensor : EnvironmentSensor{};
	interface CO2AirLevelSensor : EnvironmentSensor{};
	interface OtherAirLevelSensor : EnvironmentSensor{};
	
	interface AirInFlowRateSensor : framework::GenericSensor{
		void setInput(in simulation::environment::AirConsumer pConsumer, in long pIndex);
		simulation::environment::AirConsumer getInput();
		long getIndex();
	};
	interface AirOutFlowRateSensor : framework::GenericSensor{
		void setInput(in simulation::environment::AirProducer pProducer, in long pIndex);
		simulation::environment::AirProducer getInput();
		long getIndex();
	};
	
	interface O2AirStoreInFlowRateSensor : framework::GenericSensor{
		void setInput(in simulation::environment::O2AirConsumer pConsumer, in long pIndex);
		simulation::environment::O2AirConsumer getInput();
		long getIndex();
	};
	interface O2AirStoreOutFlowRateSensor : framework::GenericSensor{
		void setInput(in simulation::environment::O2AirProducer pProducer, in long pIndex);
		simulation::environment::O2AirProducer getInput();
		long getIndex();
	};
	interface O2AirEnvironmentInFlowRateSensor : framework::GenericSensor{
		void setInput(in simulation::environment::O2AirConsumer pConsumer, in long pIndex);
		simulation::environment::O2AirConsumer getInput();
		long getIndex();
	};
	interface O2AirEnvironmentOutFlowRateSensor : framework::GenericSensor{
		void setInput(in simulation::environment::O2AirProducer pProducer, in long pIndex);
		simulation::environment::O2AirProducer getInput();
		long getIndex();
	};
	
	interface CO2AirStoreInFlowRateSensor : framework::GenericSensor{
		void setInput(in simulation::environment::CO2AirConsumer pConsumer, in long pIndex);
		simulation::environment::CO2AirConsumer getInput();
		long getIndex();
	};
	interface CO2AirStoreOutFlowRateSensor : framework::GenericSensor{
		void setInput(in simulation::environment::CO2AirProducer pProducer, in long pIndex);
		simulation::environment::CO2AirProducer getInput();
		long getIndex();
	};
	interface CO2AirEnvironmentInFlowRateSensor : framework::GenericSensor{
		void setInput(in simulation::environment::CO2AirConsumer pConsumer, in long pIndex);
		simulation::environment::CO2AirConsumer getInput();
		long getIndex();
	};
	interface CO2AirEnvironmentOutFlowRateSensor : framework::GenericSensor{
		void setInput(in simulation::environment::CO2AirProducer pProducer, in long pIndex);
		simulation::environment::CO2AirProducer getInput();
		long getIndex();
	};
	
};
