module food{
	interface BiomassStoreSensor : framework::GenericSensor{
                void setInput(in simulation::food::BiomassStore source);
		simulation::food::BiomassStore getInput();
	};
        interface BiomassStoreLevelSensor : BiomassStoreSensor{};
	interface FoodStoreSensor : framework::GenericSensor{
                void setInput(in simulation::food::FoodStore source);
		simulation::food::FoodStore getInput();
	};
        interface FoodStoreLevelSensor : FoodStoreSensor{};
	interface BiomassFlowRateSensor : framework::GenericSensor{
		void setInput(in simulation::food::BiomassProducer source, in long indexSource, in simulation::food::BiomassConsumer destination, in long indexDestination);
		simulation::food::BiomassProducer getProducer();
		simulation::food::BiomassConsumer getConsumer();
	};
	interface FoodFlowRateSensor : framework::GenericSensor{
		void setInput(in simulation::food::FoodProducer source, in long indexSource, in simulation::food::FoodConsumer destination, in long indexDestination);
		simulation::food::FoodProducer getProducer();
		simulation::food::FoodConsumer getConsumer();
	};
};
