module food{
	interface BiomassStoreSensor : framework::GenericSensor{
                void setInput(in simulation::food::BiomassStore source);
		simulation::food::BiomassStore getInput();
	};
        interface BiomassStoreLevelSensor : BiomassStoreSensor{};
	interface FoodStoreSensor : framework::GenericSensor{
                void setInput(in simulation::food::FoodStore source);
		simulation::food::FoodStore getInput();
	};
        interface FoodStoreLevelSensor : FoodStoreSensor{};
	interface BiomassFlowRateSensor : framework::GenericSensor{
		void setInput(in simulation::food::BiomassProducer source, in simulation::food::BiomassConsumer destination);
		simulation::food::BiomassProducer getSource();
		simulation::food::BiomassConsumer getDestination();
	};
	interface FoodFlowRateSensor : framework::GenericSensor{
		void setInput(in simulation::food::FoodProducer source, in simulation::food::FoodConsumer destination);
		simulation::food::FoodProducer getSource();
		simulation::food::FoodConsumer getDestination();
	};
};
