module food{
	interface BiomassStoreSensor{
                void setInput(in simulation::food::BiomassStore source);
		simulation::food::BiomassStore getInput();
	};
        interface BiomassStoreLevelSensor : BiomassStoreSensor{};
	interface FoodStoreSensor{
                void setInput(in simulation::food::FoodStore source);
		simulation::food::FoodStore getInput();
	};
        interface FoodStoreLevelSensor : FoodStoreSensor{};
};
