module power{
	interface PowerStoreSensor : framework::GenericSensor{
                void setInput(in simulation::power::PowerStore source);
		simulation::power::PowerStore getInput();
        };
	interface PowerStoreLevelSensor : PowerStoreSensor{};
	interface PowerFlowRateSensor : framework::GenericSensor{
		void setInput(in simulation::power::PowerProducer source, in long indexSource, in simulation::power::PowerConsumer destination, in long indexDestination);
		simulation::power::PowerProducer getProducer();
		simulation::power::PowerConsumer getConsumer();
	};
};
