module water{
	interface WaterRSSensor : framework::GenericSensor{
		void setInput(in simulation::water::WaterRS source);
		simulation::water::WaterRS getInput();
	};
	interface PotableWaterStoreSensor : framework::GenericSensor{
		void setInput(in simulation::water::PotableWaterStore source);
		simulation::water::PotableWaterStore getInput();
	};
	interface GreyWaterStoreSensor : framework::GenericSensor{
		void setInput(in simulation::water::GreyWaterStore source);
		simulation::water::GreyWaterStore getInput();
	};
	interface DirtyWaterStoreSensor : framework::GenericSensor{
		void setInput(in simulation::water::DirtyWaterStore source);
		simulation::water::DirtyWaterStore getInput();
	};
        interface PotableWaterStoreLevelSensor : PotableWaterStoreSensor{};
        interface GreyWaterStoreLevelSensor : GreyWaterStoreSensor{};
        interface DirtyWaterStoreLevelSensor : DirtyWaterStoreSensor{};
	
	interface PotableWaterInFlowRateSensor : framework::GenericSensor{
		void setInput(in simulation::water::PotableWaterConsumer pConsumer, in long pIndex);
		simulation::water::PotableWaterConsumer getInput();
		long getIndex();
	};
	interface PotableWaterOutFlowRateSensor : framework::GenericSensor{
		void setInput(in simulation::water::PotableWaterProducer pProducer, in long pIndex);
		simulation::water::PotableWaterProducer getInput();
		long getIndex();
	};
	
	interface GreyWaterInFlowRateSensor : framework::GenericSensor{
		void setInput(in simulation::water::GreyWaterConsumer pConsumer, in long pIndex);
		simulation::water::GreyWaterConsumer getInput();
		long getIndex();
	};
	interface GreyWaterOutFlowRateSensor : framework::GenericSensor{
		void setInput(in simulation::water::GreyWaterProducer pProducer, in long pIndex);
		simulation::water::GreyWaterProducer getInput();
		long getIndex();
	};
	
	interface DirtyWaterInFlowRateSensor : framework::GenericSensor{
		void setInput(in simulation::water::DirtyWaterConsumer pConsumer, in long pIndex);
		simulation::water::DirtyWaterConsumer getInput();
		long getIndex();
	};
	interface DirtyWaterOutFlowRateSensor : framework::GenericSensor{
		void setInput(in simulation::water::DirtyWaterProducer pProducer, in long pIndex);
		simulation::water::DirtyWaterProducer getInput();
		long getIndex();
	};
};
