module water{
	interface WaterRSSensor : framework::GenericSensor{
		void setInput(in simulation::water::WaterRS source);
		simulation::water::WaterRS getInput();
	};
	interface PotableWaterStoreSensor : framework::GenericSensor{
		void setInput(in simulation::water::PotableWaterStore source);
		simulation::water::PotableWaterStore getInput();
	};
	interface GreyWaterStoreSensor : framework::GenericSensor{
		void setInput(in simulation::water::GreyWaterStore source);
		simulation::water::GreyWaterStore getInput();
	};
	interface DirtyWaterStoreSensor : framework::GenericSensor{
		void setInput(in simulation::water::DirtyWaterStore source);
		simulation::water::DirtyWaterStore getInput();
	};
        interface PotableWaterStoreLevelSensor : PotableWaterStoreSensor{};
        interface GreyWaterStoreLevelSensor : GreyWaterStoreSensor{};
        interface DirtyWaterStoreLevelSensor : DirtyWaterStoreSensor{};
	
	interface PotableWaterInFlowRateSensor : framework::GenericSensor{
		void setInput(in framework::PotableWaterConsumer pConsumer, in long pIndex);
		framework::PotableWaterConsumer getInput();
		long getIndex();
	};
	interface PotableWaterOutFlowRateSensor : framework::GenericSensor{
		void setInput(in framework::PotableWaterProducer pProducer, in long pIndex);
		framework::PotableWaterProducer getInput();
		long getIndex();
	};
	
	interface GreyWaterInFlowRateSensor : framework::GenericSensor{
		void setInput(in framework::GreyWaterConsumer pConsumer, in long pIndex);
		framework::GreyWaterConsumer getInput();
		long getIndex();
	};
	interface GreyWaterOutFlowRateSensor : framework::GenericSensor{
		void setInput(in framework::GreyWaterProducer pProducer, in long pIndex);
		framework::GreyWaterProducer getInput();
		long getIndex();
	};
	
	interface DirtyWaterInFlowRateSensor : framework::GenericSensor{
		void setInput(in framework::DirtyWaterConsumer pConsumer, in long pIndex);
		framework::DirtyWaterConsumer getInput();
		long getIndex();
	};
	interface DirtyWaterOutFlowRateSensor : framework::GenericSensor{
		void setInput(in framework::DirtyWaterProducer pProducer, in long pIndex);
		framework::DirtyWaterProducer getInput();
		long getIndex();
	};
};
