module air{
        interface AirRS : framework::BioModule, biosim::idl::framework::PowerConsumer, biosim::idl::framework::AirConsumer, biosim::idl::framework::AirProducer, biosim::idl::framework::CO2Producer, biosim::idl::framework::O2Producer, biosim::idl::framework::CO2Consumer{
                float getPowerConsumed();
                float getCO2Consumed();
                float getO2Produced();
                float getCO2Produced();
                boolean VCCRHasPower();
                boolean VCCRHasEnoughAir();
                boolean CRSHasPower();
                boolean CRSHasEnoughCO2();
                boolean CRSHasEnoughH2();
                boolean OGSHasPower();
                boolean OGSHasEnoughH2O();
        };
        interface O2Store : framework::Store{
        };
        interface CO2Store : framework::Store{
        };
};
