module food{
        interface BiomassRS : framework::SimBioModule, framework::PowerConsumer, framework::PotableWaterConsumer, framework::GreyWaterConsumer, framework::BiomassProducer, framework::AirConsumer, framework::AirProducer{
                ShelfList getShelves();
		Shelf createNewShelf(in PlantType pType, in float pCropArea);
        };

        interface FoodProcessor : framework::SimBioModule, framework::PowerConsumer, framework::BiomassConsumer, framework::FoodProducer{
                float getBiomassConsumed();
                float getPowerConsumed();
                float getFoodProduced();
                boolean hasPower();
                boolean hasBiomass();
        };

        interface FoodStore : framework::Store{
	};
	
        interface BiomassStore : framework::Store{
		//float addBiomatter(in float mass, in PlantType type);
		//BioMatterList takeBiomatter(in float mass);
                //void setCapacity(in float metricAmount);
                //void setLevel(in float metricAmount);
                //float getLevel();
                //float getCapacity();
	};
	
        interface Shelf{
		void harvest();
		void replant(in PlantType pType);
        };
	
	interface Plant{
        };
	
};
